package com.example.rvtypeshomework

object Server {
    fun getSites(): List<UiItem> = listOf(
        UiItem.TitleItem("СоцСети"),
        UiItem.WebSiteData(
            "Facebook",
            "https://www.facebook.com/images/fb_icon_325x325.png",
            "https://www.facebook.com"
        ),
        UiItem.WebSiteData(
            "ВКонтакте",
            "https://deskmed.ru/wp-content/files/photo-2-1536x1536.png",
            "https://vk.com/"
        ),
        UiItem.WebSiteData(
            "Linkedin",
            "https://image.similarpng.com/very-thumbnail/2020/07/Linkedin-logo-transparent-PNG.png",
            "https://ru.linkedin.com/"
        ),
        UiItem.WebSiteData(
            "Twitter",
            "https://pbs.twimg.com/media/EF5VfRBUEAABvCe.png",
            "https://twitter.com/"
        ),
        UiItem.TitleItem("Новости"),
        UiItem.WebSiteData(
            "BBC",
            "https://i1.wp.com/download.logo.wine/logo/BBC_News/BBC_News-Logo.wine.png",
            "https://www.bbc.com/news"
        ),
        UiItem.WebSiteData(
            "Риа новости",
            "https://lh3.googleusercontent.com/e-DA6X1qqxiw8fLT9Iy0F0tijUh-WHuy1xlnsR4SGlfT2jqF_j-cdCZDDLyMGFS6yDC9SGJRkg=s0-p",
            "https://ria.ru/"
        ),
        UiItem.WebSiteData(
            "БЕЛТА",
            "https://mgtp.by/wp-content/uploads/2021/12/belta3-1big2.jpg",
            "https://www.belta.by/"
        ),
        UiItem.TitleItem("Фильмы"),
        UiItem.WebSiteData(
            "КИНОПОИСК",
            "https://top10a.ru/wp-content/uploads/2021/02/scale_1200.jpg",
            "https://www.kinopoisk.ru/"
        ),
        UiItem.WebSiteData(
            "HBO",
            "https://www.snapigram.com/upload/photos/2021/08/Hc4CtuQ5oOBK2Ao4aQGU_24_7e3ad7884eab51ceb9514d6a71db343a_avatar_full.jpg",
            "https://www.hbo.com/"
        ),
        UiItem.WebSiteData(
            "Netflix",
            "https://i.pinimg.com/originals/83/28/b7/8328b735ec92dc0a41bd038830a6e67e.jpg",
            "https://www.netflix.com/by-ru/"
        ),
        UiItem.WebSiteData(
            "ИВИ",
            "https://upload.wikimedia.org/wikipedia/ru/5/5b/%D0%98%D0%B2%D0%B8-%D0%BB%D0%BE%D0%B3%D0%BE.png",
            "https://www.ivi.ru/"
        ),
        UiItem.TitleItem("Прочее"),
        UiItem.WebSiteData(
            "YouTube",
            "https://i.pinimg.com/originals/e2/54/61/e2546102e81fc5eb89aaa93a9a490d21.jpg",
            "https://www.youtube.com/"
        ),
        UiItem.WebSiteData(
            "AliExpress",
            "https://play-lh.googleusercontent.com/KpdUynlDrYAcy_UHldmmKSgOMSRiwdJZNFNv8aNSiioCQ9miZxO4MVHIrYmdvWuSBOlo",
            "https://aliexpress.ru/"
        ),
        UiItem.WebSiteData(
            "SAMSUNG",
            "https://file.liga.net/images/general/2020/09/08/20200908141029-3295.jpg?v=1599567195",
            "https://www.samsung.com/"
        ),
    )
}